# Travis CI configuration file for psycopg2

dist: xenial
sudo: required
language: python

matrix:
  include:
    - python: 2.7
    - python: 3.7
    - python: 3.6
    - python: 3.5
    - python: 3.4
      dist: trusty

install:
  - pip install -U pip setuptools wheel
  - pip install .
  - rm -rf psycopg2.egg-info
  - sudo scripts/travis_prepare.sh

script:
  - scripts/travis_test.sh

notifications:
  email: false
